datasources:
  default:
    url: jdbc:h2:mem:test-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
##
# Habilitar logs do contexto transacional
##
logger:
  levels:
    io.micronaut.transaction: DEBUG
